<?php

class MundiPaggService_DataContracts_Buyer {
	/*@var [Guid]  MundiPaggService_DataContracts_Buyer unique idenfitication. Generated by MundiPagg */
	/* @param Default: 00000000-0000-0000-0000-000000000000 (Guid empty)*/
	public $BuyerKey;
	/*@var [string] Buyer custom idenfitication */
	public $BuyerReference; 
	/*@var [DateTime] Buyer registration date in merchant */
	public $CreateDateInMerchant;
	/*@var [string] Email address */
	public $Email; 
	/*@var [string] Facebook ID */
	public $FacebookId;
	/*@var [MundiPaggService_DataContracts_GenderEnum] Gender*/
	public $GenderEnum; 
	/*@var [string] Home phone */
	public $HomePhone;
	/*@var [string] IP address */
	public $IpAddress; 
	/*@var [DateTime]  Last buyer Update */
	public $LastBuyerUpdateInMerchant;
	/*@var [string] Cel phone number */
	public $MobilePhone; 
	/*@var [string] Buyer name */
	public $Name; 
	/*@var [MundiPaggService_DataContracts_PersonTypeEnum] Person Type */
	public $PersonTypeEnum; 
	/*@var [string] Document number */
	public $TaxDocumentNumber; 
	/*@var [MundiPaggService_DataContracts_TaxDocumentTypeEnum] Document type */
	/*@param Default: CPF*/
	public $TaxDocumentTypeEnum; 
	/*@var [string] TwitterId */
	public $TwitterId;
	/*@var [string] Work Phone */
	public $WorkPhone;
	/*@var [MundiPaggService_DataContracts_BuyerAddress] Buyer Address Collection */
	public $BuyerAddressCollection;
	
	function __construct() {
		$this->BuyerKey = '00000000-0000-0000-0000-000000000000';
		$this->BuyerReference = "";
		$this->CreateDateInMerchant = null;
		$this->Email = "";
		$this->FacebookId = "";
		$this->GenderEnum = MundiPaggService_DataContracts_GenderEnum::__default;
		$this->HomePhone = "";
		$this->IpAddress = "";
		$this->LastBuyerUpdateInMerchant = null;
		$this->MobilePhone = "";
		$this->Name = "";
		$this->PersonTypeEnum = MundiPaggService_DataContracts_PersonTypeEnum::__default;
		$this->TaxDocumentNumber = "";
		$this->TaxDocumentTypeEnum = MundiPaggService_DataContracts_TaxDocumentTypeEnum::__default;
		$this->TwitterId = "";
		$this->WorkPhone = "";
		$this->BuyerAddressCollection = null;
	}
	
	function __tostring() {
		$str = "";
		$str .=  "BuyerKey: " . $this->BuyerKey . NEWLINE;
		$str .=  "BuyerReference: " . $this->BuyerReference . NEWLINE;
		$str .=  "CreateDateInMerchant: " . $this->CreateDateInMerchant . NEWLINE;
		$str .=  "Email: " . $this->Email . NEWLINE;
		$str .=  "FacebookId: " . $this->FacebookId . NEWLINE;
		$str .=  "GenderEnum: " . $this->GenderEnum . NEWLINE;
		$str .=  "HomePhone: " . $this->HomePhone . NEWLINE;
		$str .=  "IpAddress: " . $this->IpAddress . NEWLINE;
		$str .=  "LastBuyerUpdateinMerchant: " . $this->LastBuyerUpdateInMerchant . NEWLINE;
		$str .=  "MobilePhone: " . $this->MobilePhone . NEWLINE;
		$str .=  "Name: " . $this->Name . NEWLINE;
		$str .=  "PersonTypeEnum: " . $this->PersonTypeEnum = MundiPaggService_DataContracts_PersonTypeEnum::Person;
		$str .=  "TaxDocumentNumber: " . $this->TaxDocumentNumber . NEWLINE;
		$str .=  "TaxDocumentTypeEnum: " . $this->TaxDocumentTypeEnum . NEWLINE;
		$str .=  "TwitterId: " . $this->TwitterId . NEWLINE;
		$str .=  "WorkPhone: " . $this->WorkPhone . NEWLINE;
		if (is_array($this->BuyerAddressCollection)) {
			foreach($this->BuyerAddressCollection as $bAddress) {
				$str .=  "BuyerAddress: " . $bAddress . NEWLINE;
			}
		}
		
		return $str;
	}
}
